### PR TITLE
added service notice and css

### PR DESCRIPTION
**Pull request by critzo**
This PR replicates the changes from @collina 's PR, but was built locally so it could be live previewed. Here's a screenshot of the update:
image

@georgiamoon PTAL?

### CODE REVIEW

**Comment by georgiamoon** [comment]
@critzo is there a link to the live preview? are we just putting the notice on the home page? Or is there a way to put it on every page?

**Comment by critzo** [comment]
@georgiamoon There is not a live preview currently but I can do that. The PR adds it to just the front page. I can look at adding it to all pages if you would like.

**Comment by georgiamoon** [comment]
@collina what do you think about putting it on more than the front page? or a lighter version, e.g. a one line note?

**Comment by collina** [comment]
@georgiamoon: we can. I didn't want to cripple each page with my ugly design. But that's an option. Homepage may be sufficient.

**Comment by critzo** [comment]
@georgiamoon @collina You can now preview this change on https://viz-dot-mlab-staging.appspot.com/
Please let me know if you'd like to see the message altered or have it replicated on other pages.

**Review by georgiamoon — APPROVED** [review]
LGTM -- let's start here, and if we find it would be good to put on all pages, we can come back to it. thanks @critzo

**Pull request merged**
